#!/usr/bin/env node

const
 TestCrawler = require('./lib/testCrawler');

function help () {
  console.log('Usage: snipper-client <sdk> <version> <path>');
  process.exit(1);
}

const
  sdk = process.argv[2],
  version = process.argv[3];
  path = process.argv[4];

if (!sdk || !version || !path) {
  help();
}


(async () => {
  let crawler;

  try {
    crawler = new TestCrawler(sdk, version, path);

    await crawler.init();

    await crawler.sendSnippets();

    await crawler.startTesting();
  } catch (e) {
    console.error(e);
    process.exit(1);
  } finally {
    crawler.kuzzle.disconnect();
  }
})();
