name: Dead Link Check
description: Tests the existence of dead links in the documentation of a repo.

inputs:
  repo_name:
    description: The name of the repository to deploy
    required: true
  repo_branch:
    description: The branch of the repo to deploy
    required: true
  repo_version:
    description: The version of the repo to deploy
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install deps
      run: npm i --production=false
      shell: bash
    - name: Install typhoeus
      run: sudo gem install typhoeus
      shell: bash
    - name: Checks kuzdoc version
      run: npx kuzdoc --version
      shell: bash
    - name: Installs the repo
      shell: bash
    # Disabled the 13/03/2023 by Adrien
    # it gave me a weird unicode error on the IoT Backend repo
    # This is maybe too obsolete to work
    #   run: npx kuzdoc install --repo=${{ inputs.repo_name }}-${{ inputs.repo_version }} --repoBranch=${{ inputs.repo_branch }}
    # - name: Run dead links tests
    #   run: npx kuzdoc dead-links --repo=${{ inputs.repo_name }}-${{ inputs.repo_version }}
    #   shell: bash
