version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'build/*'
    - '.codepipeline/*'
  base-directory: '${CODEBUILD_SRC_DIR}'