name: Child repo triggered dead-link check

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "The name of the repository that triggered the workflow"
        required: true
      branch:
        description: "The branch of the child repo to deploy"
        required: false
      version:
        description: "The version of the product in the child repo"
        required: true

env:
  NODE_VERSION: 16

jobs:
  dead-links:
    name: Check the dead-links on the repo
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Output event inputs for debug
        run: echo "Repo ${{ github.event.inputs.repo_name }} triggered this workflow from branch ${{ github.event.inputs.branch }} v${{ github.event.inputs.version }}"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: unnecessary

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check dead links
        uses: ./.github/actions/dead-links
        with:
          repo_name: ${{ github.event.inputs.repo_name }}
          repo_version: ${{ github.event.inputs.version }}
          repo_branch: ${{ github.event.inputs.branch }}
