name: Child repo triggered dead-link check

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "The name of the repository that triggered the workflow"
        required: true
      branch:
        description: "The branch of the child repo to deploy"
        required: false
      version:
        description: "The version of the product in the child repo"
        required: true

jobs:
  dead-links:
    name: Check the dead-links on the repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output event inputs for debug
        run: echo "Repo ${{ github.event.inputs.repo_name }} triggered this workflow from branch ${{ github.event.inputs.branch }} v${{ github.event.inputs.version }}"
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: unnecessary
      - uses: ./.github/actions/dead-links
        with:
          repo_name: ${{ github.event.inputs.repo_name }}
          repo_version: ${{ github.event.inputs.version }}
          repo_branch: ${{ github.event.inputs.branch }}
