# This is a basic workflow to help you get started with Actions

name: Deploy the whole documentation to production

on:
  push:
    branches: [gha-ci]
  workflow_dispatch:

jobs:
  prepare-matrix:
    name: Prepare matrix by getting the repo names from repositories.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install python python3-pip
          pip3 install yq
        shell: bash
      - name: Get repo names
        id: set-matrix
        run: |
          export REPOS=$(cat .repos/repositories.yml | yq -c '[.[]]')
          echo "::set-output name=repo::$REPOS"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.repo }}

  deploy_framework:
    name: Deploy framework
    runs-on: ubuntu-latest
    steps:
      - name: Say something
        run: echo Deploying the framework...

  deploy_child_repo:
    name: Deploy child repo ${{ matrix.repo.repo_name }}-${{ matrix.repo.doc_version }} to PRODUCTION
    needs: [prepare-matrix, deploy_framework]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Recap of the build
        run: echo "Build and deploy documentation for ${{ matrix.repo.repo_name }}-${{ matrix.repo.doc_version }}"
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: ./.github/actions/deploy_repo.action.yml
        with:
          repo_name: ${{ matrix.repo.repo_name }}
          repo_version: ${{ matrix.repo.doc_version }}
          repo_branch: ${{ matrix.repo.stable }}
          REGION: us-west-2
          S3_BUCKET: docs.kuzzle.io
          CLOUDFRONT_ID: E3D6RP0POLCJMM
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
